/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * API version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package voicebase

type VbTaskStatusEnum string

// List of VbTaskStatusEnum
const (
	TASK_STATUS_ACCEPTED        VbTaskStatusEnum = "accepted"
	TASK_STATUS_FAILED          VbTaskStatusEnum = "failed"
	TASK_STATUS_EXCEEDEDRETRIES VbTaskStatusEnum = "exceededretries"
	TASK_STATUS_EXPIRED         VbTaskStatusEnum = "expired"
	TASK_STATUS_CANCELLED       VbTaskStatusEnum = "cancelled"
	TASK_STATUS_STORED          VbTaskStatusEnum = "stored"
	TASK_STATUS_LOADED          VbTaskStatusEnum = "loaded"
	TASK_STATUS_STARTED         VbTaskStatusEnum = "started"
	TASK_STATUS_FINISHED        VbTaskStatusEnum = "finished"
	TASK_STATUS_COMPLETED       VbTaskStatusEnum = "completed"
	TASK_STATUS_STOPPED         VbTaskStatusEnum = "stopped"
	TASK_STATUS_SKIPPED         VbTaskStatusEnum = "skipped"
	TASK_STATUS_PENDING         VbTaskStatusEnum = "pending"
)
