/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * API version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package voicebase

// Sound attributes to replace spoken words in the audio when reported by a detector
type VbAudioRedactorConfiguration struct {
	Tone int32 `json:"tone,omitempty"`

	Gain float32 `json:"gain,omitempty"`
}
