/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbClassifierConfiguration struct {

	// Classifier identifier, usually a UUID.
	ClassifierId string `json:"classifierId,omitempty"`

	// A name identifying classifiers offered by Voicebase to all customers
	ClassifierName string `json:"classifierName,omitempty"`

	// Provide a specific version (e.g. \"3.1.3\"), specify a minimum (e.g. \"3.1+\") or get the \"latest\". Defaults to \"latest\" if not specified.
	Version string `json:"version,omitempty"`

	// List of parameter values to the classifier
	Parameters []VbParameter `json:"parameters,omitempty"`
}
