/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type VbChannelConfiguration struct {

	// Speaker name on this channel. Defaults to \"SpeakerN\" where N is the channel number.
	SpeakerName string `json:"speakerName,omitempty"`

	// A description of the speaker role. Only used as metadata.
	SpeakerRole string `json:"speakerRole,omitempty"`

	// Whether this channel should be ignored for all processing.
	Ignore bool `json:"ignore,omitempty"`
}
