/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbDiarization struct {

	Band string `json:"band,omitempty"`

	Env string `json:"env,omitempty"`

	Gender string `json:"gender,omitempty"`

	Length int64 `json:"length,omitempty"`

	SpeakerLabel string `json:"speakerLabel,omitempty"`

	Start int64 `json:"start,omitempty"`
}
