/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbDetector struct {

	DetectorId string `json:"detectorId,omitempty"`

	DetectorName string `json:"detectorName,omitempty"`

	DetectorDisplayName string `json:"detectorDisplayName,omitempty"`

	DetectorType string `json:"detectorType,omitempty"`

	Detections []VbDetection `json:"detections,omitempty"`
}
