/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbErrorResponse struct {

	// Status Code
	Status int32 `json:"status,omitempty"`

	// The errors
	Errors []VbError `json:"errors,omitempty"`

	// The warnings
	Warnings []VbMessage `json:"warnings,omitempty"`

	// ref.
	Reference string `json:"reference,omitempty"`
}
