/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * API version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package voicebase

type VbIncludeTypeEnum string

// List of VbIncludeTypeEnum
const (
	INCLUDE_KNOWLEDGE  VbIncludeTypeEnum = "knowledge"
	INCLUDE_METADATA   VbIncludeTypeEnum = "metadata"
	INCLUDE_PREDICTION VbIncludeTypeEnum = "prediction"
	INCLUDE_SPOTTING   VbIncludeTypeEnum = "spotting"
	INCLUDE_STREAMS    VbIncludeTypeEnum = "streams"
	INCLUDE_TRANSCRIPT VbIncludeTypeEnum = "transcript"
)
