/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbIngestConfiguration struct {

	// Speaker name. Defaults to \"Speaker\". If this attribute is specified, all channels are mixed into a single one.
	SpeakerName string `json:"speakerName,omitempty"`

	// A description of the speaker role. Only used as metadata.
	SpeakerRole string `json:"speakerRole,omitempty"`

	// List of channels to process, mutually exclusive with \"tracks\", \"stereo\" and \"speakerName\"
	Channels []VbChannelConfiguration `json:"channels,omitempty"`

	// Indicates to process two channels of the media.
	Stereo VbStereoConfiguration `json:"stereo,omitempty"`

	// List of tracks to process, mutually exclusive with \"channels\", \"stereo\" and \"speakerName\"
	Tracks []VbTrackConfiguration `json:"tracks,omitempty"`
}
