/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

import (
	"time"
)

type VbKey struct {
	Id string `json:"id,omitempty"`

	BearerToken string `json:"bearerToken,omitempty"`

	LastSix string `json:"lastSix,omitempty"`

	Issued time.Time `json:"issued,omitempty"`

	ExpirationDate time.Time `json:"expirationDate,omitempty"`

	Expired bool `json:"expired,omitempty"`

	Scope string `json:"scope,omitempty"`
}
