/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * API version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package voicebase

type VbOccurrence struct {

	S int64 `json:"s,omitempty"`

	E int64 `json:"e,omitempty"`

	Exact string `json:"exact,omitempty"`
}
