/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbProgressTask struct {

	TaskId string `json:"taskId,omitempty"`

	Display string `json:"display,omitempty"`

	Phase string `json:"phase,omitempty"`

	Status VbTaskStatusEnum `json:"status,omitempty"`

	Dependencies []string `json:"dependencies,omitempty"`

	Dependents []string `json:"dependents,omitempty"`
}
