/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type VbProgress struct {

	Finish string `json:"finish,omitempty"`

	JobId string `json:"jobId,omitempty"`

	Start string `json:"start,omitempty"`

	Status VbTaskStatusEnum `json:"status,omitempty"`

	Tasks []VbProgressTask `json:"tasks,omitempty"`
}
