/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * API version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package voicebase

type VbStatusEnum string

// List of VbStatusEnum
const (
	ACCEPTED VbStatusEnum = "accepted"
	FAILED VbStatusEnum = "failed"
	SCHEDULED VbStatusEnum = "scheduled"
	RUNNING VbStatusEnum = "running"
	FINISHED VbStatusEnum = "finished"
)
