/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbSpeechModelConfiguration struct {

	// Specifies the language using the ISO-639-1 standard two-letter code followed by a dash and a non-standarized region code.
	Language string `json:"language,omitempty"`

	// Allows to turn on additional features of the speech engine
	Features []string `json:"features,omitempty"`

	// This allows to request speech recognition with additional extensions for specific jargon or use cases with the purpose to improve transcription accuracy
	Extensions []string `json:"extensions,omitempty"`
}
