/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbStereoConfiguration struct {

	// Description of the speaker on the left channel (Channel 0)
	Left VbChannelConfiguration `json:"left,omitempty"`

	// Description of the speaker on the right channel (Channel 1)
	Right VbChannelConfiguration `json:"right,omitempty"`
}
