/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package voicebase

type VbTrackConfiguration struct {

	// Track index.
	TrackIndex int32 `json:"trackIndex,omitempty"`

	// Speaker name. Defaults to \"Speaker\". If this attribute is specified, all channels are mixed into a single one.
	SpeakerName string `json:"speakerName,omitempty"`

	// A description of the speaker role. Only used as metadata.
	SpeakerRole string `json:"speakerRole,omitempty"`

	// List of channels to process, mutually exclusive with \"speakerName\"
	Channels []VbChannelConfiguration `json:"channels,omitempty"`
}
