/* 
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * OpenAPI spec version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type VbTranscriptRedactorConfiguration struct {

	// Sequence of characters to replace words within a transcript when reported by a detector
	Replacement string `json:"replacement,omitempty"`
}
