/*
 * Voicebase V3 API
 *
 * APIs for speech recognition and speech analytics, powering insights every business needs.
 *
 * API version: 3.0.1
 * Contact: support@voicebase.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package voicebase

type VbTranscriptFormat struct {

	Format string `json:"format,omitempty"`

	ContentType string `json:"contentType,omitempty"`

	ContentEncoding string `json:"contentEncoding,omitempty"`

	Charset string `json:"charset,omitempty"`

	Data string `json:"data,omitempty"`
}
